package com.reader.android.data.network

import com.reader.android.data.storage.RssSubscriptionDao
import com.reader.android.data.storage.RssSubscriptionEntity
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class RoomSubscriptionRepositoryTest {

    @Test
    fun `repository implements SubscriptionRepository contract`() {
        assertTrue(
            "RoomSubscriptionRepository must implement SubscriptionRepository",
            RoomSubscriptionRepository::class.java.interfaces.contains(SubscriptionRepository::class.java)
        )
    }

    @Test
    fun `add persists subscription and getAll returns it`() = runBlocking {
        val dao = FakeRssSubscriptionDao()
        val repo = RoomSubscriptionRepository(dao)

        repo.add(RssSubscription(feedUrl = "https://feed.example/rss", title = "Example"))

        val all = repo.getAll()
        assertEquals(1, all.size)
        assertEquals("https://feed.example/rss", all[0].feedUrl)
        assertEquals("Example", all[0].title)
    }

    @Test
    fun `get returns null for unknown feedUrl`() = runBlocking {
        val repo = RoomSubscriptionRepository(FakeRssSubscriptionDao())
        assertNull(repo.get("https://nonexistent/rss"))
    }

    @Test
    fun `remove deletes subscription`() = runBlocking {
        val dao = FakeRssSubscriptionDao()
        val repo = RoomSubscriptionRepository(dao)
        repo.add(RssSubscription(feedUrl = "https://feed.example/rss", title = "Example"))

        repo.remove("https://feed.example/rss")

        assertTrue(repo.getAll().isEmpty())
    }

    @Test
    fun `markUpdated updates lastUpdated and lastItemGuid`() = runBlocking {
        val dao = FakeRssSubscriptionDao()
        val repo = RoomSubscriptionRepository(dao)
        repo.add(RssSubscription(feedUrl = "https://feed.example/rss", title = "Example", lastUpdated = 0L, lastItemGuid = null))

        repo.markUpdated("https://feed.example/rss", lastItemGuid = "item-1")

        val updated = repo.get("https://feed.example/rss")!!
        assertEquals("item-1", updated.lastItemGuid)
        assertTrue("lastUpdated should advance", updated.lastUpdated > 0L)
    }

    @Test
    fun `needsUpdate returns true when subscription missing`() = runBlocking {
        val repo = RoomSubscriptionRepository(FakeRssSubscriptionDao())
        assertTrue(repo.needsUpdate("https://nonexistent/rss"))
    }

    @Test
    fun `needsUpdate returns true when lastUpdated older than maxAge`() = runBlocking {
        val dao = FakeRssSubscriptionDao()
        val repo = RoomSubscriptionRepository(dao)
        repo.add(
            RssSubscription(
                feedUrl = "https://feed.example/rss",
                title = "Example",
                lastUpdated = System.currentTimeMillis() - 60 * 60 * 1000  // 1h ago
            )
        )
        assertTrue(repo.needsUpdate("https://feed.example/rss", maxAgeMs = 30 * 60 * 1000))  // 30min
    }

    @Test
    fun `needsUpdate returns false when lastUpdated within maxAge`() = runBlocking {
        val dao = FakeRssSubscriptionDao()
        val repo = RoomSubscriptionRepository(dao)
        repo.add(
            RssSubscription(
                feedUrl = "https://feed.example/rss",
                title = "Example",
                lastUpdated = System.currentTimeMillis()  // now
            )
        )
        assertEquals(false, repo.needsUpdate("https://feed.example/rss", maxAgeMs = 30 * 60 * 1000))
    }

    /**
     * In-memory DAO double. The real [RssSubscriptionDao] is generated by
     * Room; this fake mirrors its contract so the repository logic can be
     * unit-tested without an Android runtime.
     */
    private class FakeRssSubscriptionDao : RssSubscriptionDao {
        private val store = mutableMapOf<String, RssSubscriptionEntity>()

        override suspend fun upsert(entity: RssSubscriptionEntity) {
            store[entity.feedUrl] = entity
        }

        override suspend fun delete(feedUrl: String) {
            store.remove(feedUrl)
        }

        override suspend fun get(feedUrl: String): RssSubscriptionEntity? = store[feedUrl]

        override suspend fun getAll(): List<RssSubscriptionEntity> =
            store.values.toList().sortedByDescending { it.lastUpdated }

        override suspend fun markUpdated(feedUrl: String, lastUpdated: Long, lastItemGuid: String?) {
            store[feedUrl]?.let {
                store[feedUrl] = it.copy(lastUpdated = lastUpdated, lastItemGuid = lastItemGuid)
            }
        }
    }
}
