// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/content.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class BlockType {
    @SerialName("paragraph")
    Paragraph,
    @SerialName("heading")
    Heading,
    @SerialName("image")
    Image,
    @SerialName("blockquote")
    Blockquote,
    @SerialName("code")
    Code,
    @SerialName("list")
    List,
    @SerialName("divider")
    Divider,
    @SerialName("blank")
    Blank
}

@Serializable
data class ContentBlock(
    val type: BlockType,
    val text: String? = null,
    val level: Int? = null,
    val url: String? = null,
    val alt: String? = null,
    val items: List<String>? = null,
    val ordered: Boolean? = null,
    val language: String? = null
)

@Serializable
data class ContentMeta(
    val wordCount: Int? = null,
    val charset: String? = null,
    val sourceUrl: String? = null,
    val fetchedAt: String? = null
)

@Serializable
data class Content(
    val bookId: String,
    val chapterId: String,
    val chapterIndex: Int,
    val chapterTitle: String? = null,
    val blocks: List<ContentBlock>,
    val meta: ContentMeta? = null,
    val cached: Boolean = false
)
