// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/core-command.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

@Serializable
enum class CoreCommandType {
    @SerialName("book.open")
    BookOpen,
    @SerialName("book.parse")
    BookParse,
    @SerialName("book.close")
    BookClose,
    @SerialName("chapter.list")
    ChapterList,
    @SerialName("chapter.load")
    ChapterLoad,
    @SerialName("content.load")
    ContentLoad,
    @SerialName("content.search")
    ContentSearch,
    @SerialName("content.replace")
    ContentReplace,
    @SerialName("reader.location.resolve")
    ReaderLocationResolve,
    @SerialName("reader.progress.update")
    ReaderProgressUpdate,
    @SerialName("reader.progress.snapshot")
    ReaderProgressSnapshot,
    @SerialName("source.search")
    SourceSearch,
    @SerialName("source.detail")
    SourceDetail,
    @SerialName("source.detect")
    SourceDetect,
    @SerialName("source.save")
    SourceSave,
    @SerialName("source.delete")
    SourceDelete,
    @SerialName("source.debug.run")
    SourceDebugRun,
    @SerialName("rss.list")
    RssList,
    @SerialName("rss.item.read")
    RssItemRead,
    @SerialName("rss.subscription.list")
    RssSubscriptionList,
    @SerialName("rss.subscription.add")
    RssSubscriptionAdd,
    @SerialName("rss.subscription.update")
    RssSubscriptionUpdate,
    @SerialName("rss.subscription.delete")
    RssSubscriptionDelete,
    @SerialName("rss.refresh")
    RssRefresh,
    @SerialName("tts.queue.plan")
    TtsQueuePlan,
    @SerialName("tts.queue.start")
    TtsQueueStart,
    @SerialName("tts.queue.pause")
    TtsQueuePause,
    @SerialName("tts.queue.resume")
    TtsQueueResume,
    @SerialName("tts.queue.stop")
    TtsQueueStop,
    @SerialName("tts.queue.seek")
    TtsQueueSeek,
    @SerialName("sync.snapshot")
    SyncSnapshot,
    @SerialName("sync.push")
    SyncPush,
    @SerialName("sync.pull")
    SyncPull,
    @SerialName("sync.conflict.resolve")
    SyncConflictResolve,
    @SerialName("bookshelf.list")
    BookshelfList,
    @SerialName("bookshelf.group.list")
    BookshelfGroupList,
    @SerialName("bookshelf.group.create")
    BookshelfGroupCreate,
    @SerialName("bookshelf.group.update")
    BookshelfGroupUpdate,
    @SerialName("bookshelf.group.delete")
    BookshelfGroupDelete,
    @SerialName("bookshelf.book.add")
    BookshelfBookAdd,
    @SerialName("bookshelf.book.remove")
    BookshelfBookRemove,
    @SerialName("bookshelf.book.update")
    BookshelfBookUpdate,
    @SerialName("cache.clear")
    CacheClear,
    @SerialName("cache.book.prefetch")
    CacheBookPrefetch,
    @SerialName("cache.book.status")
    CacheBookStatus
}

@Serializable
data class CoreCommand(
    val type: CoreCommandType,
    val payload: Map<String, JsonElement> = emptyMap(),
    val correlationId: String? = null,
    val requestId: String? = null
)
