// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/core-event.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

@Serializable
enum class CoreEventType {
    @SerialName("book.opened")
    BookOpened,
    @SerialName("book.parsed")
    BookParsed,
    @SerialName("book.open.failed")
    BookOpenFailed,
    @SerialName("book.parse.failed")
    BookParseFailed,
    @SerialName("chapter.listed")
    ChapterListed,
    @SerialName("chapter.list.failed")
    ChapterListFailed,
    @SerialName("content.loaded")
    ContentLoaded,
    @SerialName("content.load.failed")
    ContentLoadFailed,
    @SerialName("content.search.completed")
    ContentSearchCompleted,
    @SerialName("content.replace.applied")
    ContentReplaceApplied,
    @SerialName("reader.location.resolved")
    ReaderLocationResolved,
    @SerialName("reader.location.resolve.failed")
    ReaderLocationResolveFailed,
    @SerialName("reader.progress.updated")
    ReaderProgressUpdated,
    @SerialName("reader.progress.snapshot.ready")
    ReaderProgressSnapshotReady,
    @SerialName("source.search.completed")
    SourceSearchCompleted,
    @SerialName("source.search.failed")
    SourceSearchFailed,
    @SerialName("source.detail.loaded")
    SourceDetailLoaded,
    @SerialName("source.detail.failed")
    SourceDetailFailed,
    @SerialName("source.detected")
    SourceDetected,
    @SerialName("source.detect.failed")
    SourceDetectFailed,
    @SerialName("source.saved")
    SourceSaved,
    @SerialName("source.save.failed")
    SourceSaveFailed,
    @SerialName("source.deleted")
    SourceDeleted,
    @SerialName("source.delete.failed")
    SourceDeleteFailed,
    @SerialName("source.debug.completed")
    SourceDebugCompleted,
    @SerialName("source.debug.failed")
    SourceDebugFailed,
    @SerialName("rss.listed")
    RssListed,
    @SerialName("rss.list.failed")
    RssListFailed,
    @SerialName("rss.item.loaded")
    RssItemLoaded,
    @SerialName("rss.item.load.failed")
    RssItemLoadFailed,
    @SerialName("rss.subscription.listed")
    RssSubscriptionListed,
    @SerialName("rss.subscription.added")
    RssSubscriptionAdded,
    @SerialName("rss.subscription.updated")
    RssSubscriptionUpdated,
    @SerialName("rss.subscription.deleted")
    RssSubscriptionDeleted,
    @SerialName("rss.subscription.operation.failed")
    RssSubscriptionOperationFailed,
    @SerialName("rss.refreshed")
    RssRefreshed,
    @SerialName("rss.refresh.failed")
    RssRefreshFailed,
    @SerialName("tts.queue.planned")
    TtsQueuePlanned,
    @SerialName("tts.queue.plan.failed")
    TtsQueuePlanFailed,
    @SerialName("tts.queue.started")
    TtsQueueStarted,
    @SerialName("tts.queue.paused")
    TtsQueuePaused,
    @SerialName("tts.queue.resumed")
    TtsQueueResumed,
    @SerialName("tts.queue.stopped")
    TtsQueueStopped,
    @SerialName("tts.queue.progress")
    TtsQueueProgress,
    @SerialName("tts.queue.failed")
    TtsQueueFailed,
    @SerialName("sync.snapshot.ready")
    SyncSnapshotReady,
    @SerialName("sync.snapshot.failed")
    SyncSnapshotFailed,
    @SerialName("sync.pushed")
    SyncPushed,
    @SerialName("sync.push.failed")
    SyncPushFailed,
    @SerialName("sync.pulled")
    SyncPulled,
    @SerialName("sync.pull.failed")
    SyncPullFailed,
    @SerialName("sync.conflict.detected")
    SyncConflictDetected,
    @SerialName("sync.conflict.resolved")
    SyncConflictResolved,
    @SerialName("sync.conflict.resolve.failed")
    SyncConflictResolveFailed,
    @SerialName("bookshelf.listed")
    BookshelfListed,
    @SerialName("bookshelf.list.failed")
    BookshelfListFailed,
    @SerialName("bookshelf.group.listed")
    BookshelfGroupListed,
    @SerialName("bookshelf.group.created")
    BookshelfGroupCreated,
    @SerialName("bookshelf.group.updated")
    BookshelfGroupUpdated,
    @SerialName("bookshelf.group.deleted")
    BookshelfGroupDeleted,
    @SerialName("bookshelf.group.operation.failed")
    BookshelfGroupOperationFailed,
    @SerialName("bookshelf.book.added")
    BookshelfBookAdded,
    @SerialName("bookshelf.book.removed")
    BookshelfBookRemoved,
    @SerialName("bookshelf.book.updated")
    BookshelfBookUpdated,
    @SerialName("bookshelf.book.operation.failed")
    BookshelfBookOperationFailed,
    @SerialName("cache.cleared")
    CacheCleared,
    @SerialName("cache.book.prefetched")
    CacheBookPrefetched,
    @SerialName("cache.book.status.updated")
    CacheBookStatusUpdated,
    @SerialName("cache.operation.failed")
    CacheOperationFailed
}

@Serializable
data class CoreEvent(
    val type: CoreEventType,
    val payload: Map<String, JsonElement> = emptyMap(),
    val correlationId: String? = null,
    val requestId: String? = null,
    val timestamp: String? = null
)
