// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/host-request.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

@Serializable
enum class HostRequestType {
    @SerialName("http.execute")
    HttpExecute,
    @SerialName("http.cancel")
    HttpCancel,
    @SerialName("webview.open")
    WebviewOpen,
    @SerialName("webview.close")
    WebviewClose,
    @SerialName("webview.evaluate")
    WebviewEvaluate,
    @SerialName("cookie.get")
    CookieGet,
    @SerialName("cookie.set")
    CookieSet,
    @SerialName("cookie.clear")
    CookieClear,
    @SerialName("file.read")
    FileRead,
    @SerialName("file.write")
    FileWrite,
    @SerialName("file.delete")
    FileDelete,
    @SerialName("storage.path")
    StoragePath,
    @SerialName("credential.get")
    CredentialGet,
    @SerialName("credential.set")
    CredentialSet,
    @SerialName("credential.delete")
    CredentialDelete,
    @SerialName("tts.system.start")
    TtsSystemStart,
    @SerialName("tts.system.stop")
    TtsSystemStop,
    @SerialName("tts.system.pause")
    TtsSystemPause,
    @SerialName("tts.system.resume")
    TtsSystemResume,
    @SerialName("permission.request")
    PermissionRequest,
    @SerialName("permission.check")
    PermissionCheck,
    @SerialName("background.schedule")
    BackgroundSchedule,
    @SerialName("background.cancel")
    BackgroundCancel,
    @SerialName("notification.show")
    NotificationShow,
    @SerialName("notification.cancel")
    NotificationCancel,
    @SerialName("share.invoke")
    ShareInvoke,
    @SerialName("clipboard.copy")
    ClipboardCopy,
    @SerialName("clipboard.paste")
    ClipboardPaste,
    @SerialName("device.vibrate")
    DeviceVibrate,
    @SerialName("device.screen.keep-on")
    DeviceScreenKeepOn,
    @SerialName("device.screen.release")
    DeviceScreenRelease
}

@Serializable
enum class HostInitiator {
    @SerialName("core")
    Core,
    @SerialName("reducer")
    Reducer
}

@Serializable
data class HostRequest(
    val type: HostRequestType,
    val payload: Map<String, JsonElement> = emptyMap(),
    val correlationId: String? = null,
    val requestId: String? = null,
    val initiator: HostInitiator? = null
)
