// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/motion.schema.json + fixtures/motion.fixtures.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class MotionId {
    @SerialName("app.firstOpen.enter")
    AppFirstOpenEnter,
    @SerialName("app.route.push.forward")
    AppRoutePushForward,
    @SerialName("app.route.pop.backward")
    AppRoutePopBackward,
    @SerialName("app.route.replace")
    AppRouteReplace,
    @SerialName("bookshelf.view.switch")
    BookshelfViewSwitch,
    @SerialName("button.activate")
    ButtonActivate,
    @SerialName("card.press")
    CardPress,
    @SerialName("card.select")
    CardSelect,
    @SerialName("card.route")
    CardRoute,
    @SerialName("chip.item.select")
    ChipItemSelect,
    @SerialName("destructive.confirm.commit")
    DestructiveConfirmCommit,
    @SerialName("dropdown.menu.collapse")
    DropdownMenuCollapse,
    @SerialName("dropdown.menu.expand")
    DropdownMenuExpand,
    @SerialName("dropdown.option.select")
    DropdownOptionSelect,
    @SerialName("dropdown.trigger.press")
    DropdownTriggerPress,
    @SerialName("feedback.toast.enter")
    FeedbackToastEnter,
    @SerialName("feedback.toast.update")
    FeedbackToastUpdate,
    @SerialName("feedback.toast.exit")
    FeedbackToastExit,
    @SerialName("filter.apply.commit")
    FilterApplyCommit,
    @SerialName("filter.item.toggle")
    FilterItemToggle,
    @SerialName("input.blur")
    InputBlur,
    @SerialName("input.clear")
    InputClear,
    @SerialName("input.focus")
    InputFocus,
    @SerialName("input.focus-blur")
    InputFocusBlur,
    @SerialName("input.submit")
    InputSubmit,
    @SerialName("listRow.select")
    ListRowSelect,
    @SerialName("motion.interrupt.cancel")
    MotionInterruptCancel,
    @SerialName("motion.interrupt.completeThenReplace")
    MotionInterruptCompleteThenReplace,
    @SerialName("motion.interrupt.redirect")
    MotionInterruptRedirect,
    @SerialName("overlay.dialog.enter")
    OverlayDialogEnter,
    @SerialName("overlay.dialog.enter-exit")
    OverlayDialogEnterExit,
    @SerialName("overlay.dialog.exit")
    OverlayDialogExit,
    @SerialName("overlay.keyboard.enter-exit")
    OverlayKeyboardEnterExit,
    @SerialName("overlay.sheet.enter")
    OverlaySheetEnter,
    @SerialName("overlay.sheet.enter-exit")
    OverlaySheetEnterExit,
    @SerialName("overlay.sheet.exit")
    OverlaySheetExit,
    @SerialName("reader.chapter.jump")
    ReaderChapterJump,
    @SerialName("reader.control.dock.drag")
    ReaderControlDockDrag,
    @SerialName("reader.control.dock.longPress")
    ReaderControlDockLongPress,
    @SerialName("reader.control.dock.rebound")
    ReaderControlDockRebound,
    @SerialName("reader.control.dock.release")
    ReaderControlDockRelease,
    @SerialName("reader.control.handle.press")
    ReaderControlHandlePress,
    @SerialName("reader.control.handle.release")
    ReaderControlHandleRelease,
    @SerialName("reader.control.hide")
    ReaderControlHide,
    @SerialName("reader.entry.actionToImmersive")
    ReaderEntryActionToImmersive,
    @SerialName("reader.entry.coverToImmersive")
    ReaderEntryCoverToImmersive,
    @SerialName("reader.module.switch")
    ReaderModuleSwitch,
    @SerialName("reader.page.turn.next-prev")
    ReaderPageTurnNextPrev,
    @SerialName("reader.quick.promote")
    ReaderQuickPromote,
    @SerialName("reader.session.autoPage.start")
    ReaderSessionAutoPageStart,
    @SerialName("reader.session.capsule.enter")
    ReaderSessionCapsuleEnter,
    @SerialName("reader.session.capsule.update")
    ReaderSessionCapsuleUpdate,
    @SerialName("reader.session.capsule.exit")
    ReaderSessionCapsuleExit,
    @SerialName("reader.session.capsule.switch")
    ReaderSessionCapsuleSwitch,
    @SerialName("reader.session.capsule.control.press-toggle")
    ReaderSessionCapsuleControlPressToggle,
    @SerialName("reader.session.capsule.countdownTick")
    ReaderSessionCapsuleCountdownTick,
    @SerialName("reader.session.capsule.voiceIcon.active")
    ReaderSessionCapsuleVoiceIconActive,
    @SerialName("reader.session.controlSpace.enter")
    ReaderSessionControlSpaceEnter,
    @SerialName("reader.session.controlSpace.update")
    ReaderSessionControlSpaceUpdate,
    @SerialName("reader.session.controlSpace.exit")
    ReaderSessionControlSpaceExit,
    @SerialName("reader.session.tts.start")
    ReaderSessionTtsStart,
    @SerialName("reader.sourceSwitch.open-close")
    ReaderSourceSwitchOpenClose,
    @SerialName("search.state.replace")
    SearchStateReplace,
    @SerialName("segment.item.switch")
    SegmentItemSwitch,
    @SerialName("selection.group.toggle")
    SelectionGroupToggle,
    @SerialName("selection.item.toggle")
    SelectionItemToggle,
    @SerialName("selection.option.toggle")
    SelectionOptionToggle,
    @SerialName("selection.range.show")
    SelectionRangeShow,
    @SerialName("selection.toolbar.action")
    SelectionToolbarAction,
    @SerialName("selection.toolbar.exit")
    SelectionToolbarExit,
    @SerialName("slider.drag.start")
    SliderDragStart,
    @SerialName("slider.drag.update")
    SliderDragUpdate,
    @SerialName("slider.drag.release")
    SliderDragRelease,
    @SerialName("state.content.replace")
    StateContentReplace,
    @SerialName("state.loading.inline")
    StateLoadingInline,
    @SerialName("stepper.press")
    StepperPress,
    @SerialName("stepper.value.change")
    StepperValueChange,
    @SerialName("tab.item.select")
    TabItemSelect,
    @SerialName("tab.switch")
    TabSwitch,
    @SerialName("toggle.switch")
    ToggleSwitch,
    @SerialName("tooling.mode.switch")
    ToolingModeSwitch,
    @SerialName("viewport.orientation.prepare")
    ViewportOrientationPrepare,
    @SerialName("viewport.orientation.reshape")
    ViewportOrientationReshape,
    @SerialName("viewport.orientation.settle")
    ViewportOrientationSettle
}

@Serializable
enum class MotionEasing {
    @SerialName("ease")
    Ease,
    @SerialName("ease-in")
    EaseIn,
    @SerialName("ease-out")
    EaseOut,
    @SerialName("ease-in-out")
    EaseInOut,
    @SerialName("linear")
    Linear,
    @SerialName("none")
    None
}

@Serializable
data class MotionTokens(
    val durationToken: String? = null,
    val easingToken: String? = null
)

@Serializable
data class Motion(
    val id: MotionId,
    val durationMs: Int,
    val easing: MotionEasing,
    val tokens: MotionTokens? = null,
    val guardRules: List<String>? = null,
    val reducedMotion: MotionReducedMotion? = null,
    val deprecated: Boolean = false
)

@Serializable
data class MotionReducedMotion(
    val forceZeroDuration: Boolean,
    val directManipulation: Boolean,
    val sourceRule: String? = null
)

object MotionSpecRegistry {
    val all: List<Motion> = listOf(
    Motion(
        id = MotionId.AppFirstOpenEnter,
        durationMs = 280,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "app.motion.duration.firstOpen", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.AppRoutePushForward,
        durationMs = 160,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "app.motion.duration.tabSwitch", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:redirect", "asyncGuard:discardStaleRouteResult"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.AppRoutePopBackward,
        durationMs = 160,
        easing = MotionEasing.EaseIn,
        tokens = MotionTokens(durationToken = "app.motion.duration.tabSwitch", easingToken = "app.motion.easing.exit"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:cancel", "focusReturn:restorePreviousRoute"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.AppRouteReplace,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.stateReplace", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:completeThenReplace", "asyncGuard:discardStaleRouteResult"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.BookshelfViewSwitch,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.tabSwitch", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:redirect", "layoutStable:preserveScrollAnchor"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ButtonActivate,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.buttonActivate", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:hitAreaStable", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.TabSwitch,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.tabSwitch", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:redirect", "layoutStable:indicatorDoesNotPushLayout"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.TabItemSelect,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.tabSelect", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:cancel", "layoutStable:hitAreaStable"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ToggleSwitch,
        durationMs = 140,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.toggleSwitch", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:hitAreaStable", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ChipItemSelect,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.chipSelect", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:hitAreaStable", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.DropdownMenuExpand,
        durationMs = 160,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "app.motion.duration.dropdownExpand", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:trapFocus", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.DropdownMenuCollapse,
        durationMs = 120,
        easing = MotionEasing.EaseIn,
        tokens = MotionTokens(durationToken = "app.motion.duration.dropdownCollapse", easingToken = "app.motion.easing.exit"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.OverlaySheetEnter,
        durationMs = 240,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.overlay", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.OverlaySheetExit,
        durationMs = 240,
        easing = MotionEasing.EaseIn,
        tokens = MotionTokens(durationToken = "reader.motion.duration.overlay", easingToken = "app.motion.easing.exit"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.OverlayDialogEnter,
        durationMs = 240,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.overlay", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:trapFocus", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.OverlayDialogExit,
        durationMs = 240,
        easing = MotionEasing.EaseIn,
        tokens = MotionTokens(durationToken = "reader.motion.duration.overlay", easingToken = "app.motion.easing.exit"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.FeedbackToastEnter,
        durationMs = 180,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "app.motion.duration.feedbackToast", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:updateInSameHost"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.FeedbackToastExit,
        durationMs = 180,
        easing = MotionEasing.EaseIn,
        tokens = MotionTokens(durationToken = "app.motion.duration.feedbackToast", easingToken = "app.motion.easing.exit"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:updateInSameHost"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.InputFocus,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.inputFocus", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "keyboardInset:platformNative", "focusReturn:keepTarget", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.InputBlur,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.inputFocus", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "keyboardInset:platformNative", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.SearchStateReplace,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.searchState", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "asyncGuard:discardStaleSearchResult", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.StateContentReplace,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.stateReplace", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:preserveScrollAnchor", "interrupt:completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.StateLoadingInline,
        durationMs = 800,
        easing = MotionEasing.Linear,
        tokens = MotionTokens(durationToken = "reader.motion.duration.loadingSpin", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderPageTurnNextPrev,
        durationMs = 220,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.pageTurn", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:noTextReflow", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderChapterJump,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.base", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "asyncGuard:discardStaleContent", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderModuleSwitch,
        durationMs = 200,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.panel", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "transitionGuard:overlayNullIntermediate", "focusReturn:restoreTarget", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderEntryCoverToImmersive,
        durationMs = 240,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.readerEntry", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "asyncGuard:latestIntentWins", "interrupt:cancel|redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderEntryActionToImmersive,
        durationMs = 240,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.readerEntry", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "asyncGuard:latestIntentWins", "interrupt:cancel|redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionCapsuleEnter,
        durationMs = 160,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.capsuleEnter", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "layoutStable:capsuleHitAreaStable"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionCapsuleUpdate,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.capsuleControl", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "layoutStable:localUpdateOnly"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionCapsuleExit,
        durationMs = 160,
        easing = MotionEasing.EaseIn,
        tokens = MotionTokens(durationToken = "reader.motion.duration.capsuleEnter", easingToken = "app.motion.easing.exit"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "focusReturn:restoreTarget"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionCapsuleSwitch,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.capsuleEnter", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "interrupt:completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionCapsuleCountdownTick,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.capsuleTick", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "layoutStable:localUpdateOnly"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionCapsuleVoiceIconActive,
        durationMs = 960,
        easing = MotionEasing.EaseInOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.voicePulse", easingToken = "app.motion.easing.reshape"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "layoutStable:localUpdateOnly"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionTtsStart,
        durationMs = 200,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.sessionReturn", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "asyncGuard:latestIntentWins"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionAutoPageStart,
        durationMs = 200,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.sessionReturn", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "asyncGuard:latestIntentWins"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSourceSwitchOpenClose,
        durationMs = 240,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.overlay", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderControlHandlePress,
        durationMs = 0,
        easing = MotionEasing.None,
        tokens = MotionTokens(durationToken = "reader.motion.duration.instant", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("dragMustFollowFinger:noEasing"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = true, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderControlHandleRelease,
        durationMs = 120,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.handleSnap", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("releaseToSnap:afterReleaseOnly"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = false, directManipulation = true, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderControlDockLongPress,
        durationMs = 320,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.handleLongPress", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("dragMustFollowFinger:noEasing", "layoutStable:hitAreaStable"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = false, directManipulation = true, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderControlDockDrag,
        durationMs = 0,
        easing = MotionEasing.None,
        tokens = MotionTokens(durationToken = "reader.motion.duration.instant", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("dragMustFollowFinger:noEasing", "layoutStable:clampToReaderFrame"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = true, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderControlDockRelease,
        durationMs = 120,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.handleSnap", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("releaseToSnap:afterReleaseOnly", "layoutStable:clampToReaderFrame"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = false, directManipulation = true, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderControlDockRebound,
        durationMs = 120,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.handleSnap", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("releaseToSnap:afterReleaseOnly", "layoutStable:clampToReaderFrame", "interrupt:completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = false, directManipulation = true, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderControlHide,
        durationMs = 240,
        easing = MotionEasing.EaseIn,
        tokens = MotionTokens(durationToken = "reader.motion.duration.overlay", easingToken = "app.motion.easing.exit"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.SliderDragStart,
        durationMs = 0,
        easing = MotionEasing.None,
        tokens = MotionTokens(durationToken = "reader.motion.duration.instant", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("dragMustFollowFinger:noEasing"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = true, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.SliderDragUpdate,
        durationMs = 0,
        easing = MotionEasing.None,
        tokens = MotionTokens(durationToken = "reader.motion.duration.instant", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("dragMustFollowFinger:noEasing"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = true, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.SliderDragRelease,
        durationMs = 120,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.handleSnap", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("releaseToSnap:afterReleaseOnly"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = false, directManipulation = true, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.ViewportOrientationReshape,
        durationMs = 240,
        easing = MotionEasing.EaseInOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.viewportReshape", easingToken = "app.motion.easing.reshape"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:clampAnchors", "interrupt:completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ViewportOrientationSettle,
        durationMs = 240,
        easing = MotionEasing.EaseInOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.orientationSettle", easingToken = "app.motion.easing.reshape"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:restoreAnchors"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ViewportOrientationPrepare,
        durationMs = 80,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.orientationFreeze", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:freezeAnchors"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionControlSpaceEnter,
        durationMs = 180,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.runningSpace", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "layoutStable:singleController"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionControlSpaceExit,
        durationMs = 180,
        easing = MotionEasing.EaseIn,
        tokens = MotionTokens(durationToken = "reader.motion.duration.runningSpace", easingToken = "app.motion.easing.exit"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "layoutStable:singleController"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.OverlayKeyboardEnterExit,
        durationMs = 240,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.overlay", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "keyboardInset:platformNative", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.MotionInterruptCancel,
        durationMs = 80,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.interruptSettle", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("interrupt:cancel|redirect|completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = false, directManipulation = false, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.MotionInterruptRedirect,
        durationMs = 80,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.interruptSettle", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("interrupt:cancel|redirect|completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = false, directManipulation = false, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.MotionInterruptCompleteThenReplace,
        durationMs = 80,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.interruptSettle", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("interrupt:cancel|redirect|completeThenReplace", "asyncGuard:cancelOnRouteReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = false, directManipulation = false, sourceRule = null),
        deprecated = false
    ),
    Motion(
        id = MotionId.CardPress,
        durationMs = 80,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.buttonPress", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:hitAreaStable", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.CardSelect,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.buttonActivate", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:selectionDoesNotReflow", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.CardRoute,
        durationMs = 160,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "app.motion.duration.tabSwitch", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "asyncGuard:latestIntentWins", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.DestructiveConfirmCommit,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.filterCommit", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "asyncGuard:confirmationRequired", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.DropdownOptionSelect,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.dropdownSelect", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.DropdownTriggerPress,
        durationMs = 80,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.dropdownPress", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:hitAreaStable", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.FeedbackToastUpdate,
        durationMs = 180,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.feedbackToast", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "interrupt:updateInSameHost", "layoutStable:toastHostStable"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.FilterApplyCommit,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.filterCommit", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "asyncGuard:discardStaleFilterResult", "interrupt:completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.FilterItemToggle,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.chipSelect", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:hitAreaStable", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.InputClear,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.inputFocus", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:keepTarget", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.InputFocusBlur,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.inputFocus", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "keyboardInset:platformNative", "focusReturn:restoreTarget", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.InputSubmit,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.searchState", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "asyncGuard:discardStaleSubmitResult", "interrupt:completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ListRowSelect,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.buttonActivate", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:hitAreaStable", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.OverlayDialogEnterExit,
        durationMs = 240,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.overlay", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.OverlaySheetEnterExit,
        durationMs = 240,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.overlay", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderQuickPromote,
        durationMs = 120,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "reader.motion.duration.fast", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:noTextReflow", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionCapsuleControlPressToggle,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.capsuleControl", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "layoutStable:hitAreaStable"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ReaderSessionControlSpaceUpdate,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "reader.motion.duration.capsuleControl", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "activeSession:mutex", "layoutStable:localUpdateOnly"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.SegmentItemSwitch,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.tabSelect", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:indicatorDoesNotPushLayout", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.SelectionGroupToggle,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.chipSelect", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:selectionDoesNotReflow", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.SelectionItemToggle,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.chipSelect", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:selectionDoesNotReflow", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.SelectionOptionToggle,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.chipSelect", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:selectionDoesNotReflow", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.SelectionRangeShow,
        durationMs = 160,
        easing = MotionEasing.EaseOut,
        tokens = MotionTokens(durationToken = "app.motion.duration.selectionToolbar", easingToken = "app.motion.easing.enter"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:noTextReflow", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.SelectionToolbarAction,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.selectionToolbar", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:keepTarget", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.SelectionToolbarExit,
        durationMs = 160,
        easing = MotionEasing.EaseIn,
        tokens = MotionTokens(durationToken = "app.motion.duration.selectionToolbar", easingToken = "app.motion.easing.exit"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "focusReturn:restoreTarget", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.StepperPress,
        durationMs = 80,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.buttonPress", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:hitAreaStable", "interrupt:cancel"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.StepperValueChange,
        durationMs = 120,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.numericCommit", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:numericWidthStable", "interrupt:redirect"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    ),
    Motion(
        id = MotionId.ToolingModeSwitch,
        durationMs = 160,
        easing = MotionEasing.Ease,
        tokens = MotionTokens(durationToken = "app.motion.duration.stateReplace", easingToken = "app.motion.easing.standard"),
        guardRules = listOf("reducedMotion:forceZeroDuration", "layoutStable:preserveRouteShell", "interrupt:completeThenReplace"),
        reducedMotion = MotionReducedMotion(forceZeroDuration = true, directManipulation = false, sourceRule = "reducedMotion:forceZeroDuration"),
        deprecated = false
    )
    )

    val byId: Map<MotionId, Motion> = all.associateBy { it.id }

    fun spec(id: MotionId): Motion? = byId[id]
}
