// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/progress-location.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

@Serializable
enum class LocatorType {
    @SerialName("char-offset")
    CharOffset,
    @SerialName("paragraph-index")
    ParagraphIndex,
    @SerialName("selector")
    Selector,
    @SerialName("range")
    Range
}

@Serializable
enum class ProgressSource {
    @SerialName("user-read")
    UserRead,
    @SerialName("chapter-jump")
    ChapterJump,
    @SerialName("sync-restore")
    SyncRestore,
    @SerialName("search-jump")
    SearchJump,
    @SerialName("tts-follow")
    TtsFollow
}

@Serializable
data class LocatorRange(
    val start: Map<String, JsonElement>? = null,
    val end: Map<String, JsonElement>? = null
)

@Serializable
data class Locator(
    val type: LocatorType,
    val charOffset: Int? = null,
    val paragraphIndex: Int? = null,
    val selector: String? = null,
    val range: LocatorRange? = null
)

@Serializable
data class ProgressLocation(
    val bookId: String,
    val chapterIndex: Int,
    val chapterId: String? = null,
    val locator: Locator,
    val progress: Double? = null,
    val pageIndex: Int? = null,
    val updatedAt: String? = null,
    val source: ProgressSource? = null
)
