// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/state-rule.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

@Serializable
enum class StateRuleKind {
    @SerialName("mutex")
    Mutex,
    @SerialName("async-guard")
    AsyncGuard,
    @SerialName("required-with")
    RequiredWith,
    @SerialName("forbidden-with")
    ForbiddenWith,
    @SerialName("transition-guard")
    TransitionGuard
}

@Serializable
enum class StateRuleSeverity {
    @SerialName("error")
    Error,
    @SerialName("warn")
    Warn
}

@Serializable
enum class StateRuleSlice {
    @SerialName("slice-1")
    Slice1,
    @SerialName("slice-2")
    Slice2,
    @SerialName("slice-3")
    Slice3,
    @SerialName("slice-4")
    Slice4,
    @SerialName("slice-5")
    Slice5,
    @SerialName("slice-6")
    Slice6
}

@Serializable
data class StateRuleTarget(
    val fields: List<String>,
    val slices: List<StateRuleSlice>? = null
)

@Serializable
data class StateRuleConstraint(
    val maxNonNull: Int? = null,
    val guardField: String? = null,
    val guardValue: JsonElement? = null,
    val requiredField: String? = null,
    val forbiddenField: String? = null,
    val fromStates: List<String>? = null,
    val toStates: List<String>? = null,
    val description: String? = null
)

@Serializable
data class StateRule(
    val ruleId: String,
    val kind: StateRuleKind,
    val target: StateRuleTarget,
    val constraint: StateRuleConstraint,
    val severity: StateRuleSeverity = StateRuleSeverity.Error,
    val deprecated: Boolean = false
)
