// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/sync-conflict.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

@Serializable
enum class SyncConflictType {
    @SerialName("progress")
    Progress,
    @SerialName("bookshelf")
    Bookshelf,
    @SerialName("bookmark")
    Bookmark,
    @SerialName("annotation")
    Annotation,
    @SerialName("source-config")
    SourceConfig
}

@Serializable
enum class SyncConflictResolution {
    @SerialName("keep-local")
    KeepLocal,
    @SerialName("keep-remote")
    KeepRemote,
    @SerialName("merge")
    Merge,
    @SerialName("keep-both")
    KeepBoth,
    @SerialName("skip")
    Skip
}

@Serializable
data class SyncConflict(
    val conflictId: String,
    val bookId: String,
    val type: SyncConflictType,
    val local: Map<String, JsonElement>,
    val remote: Map<String, JsonElement>,
    val localUpdatedAt: String? = null,
    val remoteUpdatedAt: String? = null,
    val resolution: SyncConflictResolution? = null,
    val mergeHint: Map<String, JsonElement>? = null,
    val detectedAt: String? = null
)
