// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/token.schema.json + fixtures/token.fixtures.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class TokenCategory {
    @SerialName("color")
    Color,
    @SerialName("font")
    Font,
    @SerialName("type")
    Type,
    @SerialName("spacing")
    Spacing,
    @SerialName("size")
    Size,
    @SerialName("radius")
    Radius,
    @SerialName("shadow")
    Shadow,
    @SerialName("elevation")
    Elevation,
    @SerialName("z-index")
    ZIndex,
    @SerialName("text-constraint")
    TextConstraint,
    @SerialName("motion-duration")
    MotionDuration,
    @SerialName("motion-easing")
    MotionEasing
}

@Serializable
data class TokenPlatforms(
    val swift: String? = null,
    val kotlin: String? = null,
    val arkts: String? = null
)

@Serializable
data class Token(
    val name: String,
    val category: TokenCategory,
    val value: String,
    val platforms: TokenPlatforms? = null,
    val deprecated: Boolean = false
)

object TokenRegistry {
    val all: List<Token> = listOf(
    Token(
        name = "--reader-ds-color-paper",
        category = TokenCategory.Color,
        value = "#fff8f4",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-paper-bright",
        category = TokenCategory.Color,
        value = "#fff8f1",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-surface",
        category = TokenCategory.Color,
        value = "rgba(255,255,255,0.88)",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-surface-soft",
        category = TokenCategory.Color,
        value = "rgba(255,252,248,0.72)",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-ink",
        category = TokenCategory.Color,
        value = "#1f1b17",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-control-ink",
        category = TokenCategory.Color,
        value = "#41484c",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-muted",
        category = TokenCategory.Color,
        value = "#756f69",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-border",
        category = TokenCategory.Color,
        value = "#c1c7cd",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-primary",
        category = TokenCategory.Color,
        value = "#366179",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-primary-dark",
        category = TokenCategory.Color,
        value = "#274f66",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-accent",
        category = TokenCategory.Color,
        value = "#f48b13",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-bottom-bar-bg",
        category = TokenCategory.Color,
        value = "#fbf2eb",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-floating-control-bg",
        category = TokenCategory.Color,
        value = "#fbf2eb",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-floating-control-bg-alt",
        category = TokenCategory.Color,
        value = "#eae1da",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-meta-bg",
        category = TokenCategory.Color,
        value = "#f5ece6",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-color-rss-unread",
        category = TokenCategory.Color,
        value = "#2F6F93",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-font-sans",
        category = TokenCategory.Font,
        value = "-apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"PingFang SC\", \"Microsoft YaHei\", sans-serif",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-font-serif",
        category = TokenCategory.Font,
        value = "\"Songti SC\", \"STSong\", \"Noto Serif CJK SC\", \"Source Han Serif SC\", serif",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-type-app-title-size",
        category = TokenCategory.Type,
        value = "20px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-type-page-title-size",
        category = TokenCategory.Type,
        value = "20px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-type-section-title-size",
        category = TokenCategory.Type,
        value = "15px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-type-book-title-size",
        category = TokenCategory.Type,
        value = "14px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-type-book-meta-size",
        category = TokenCategory.Type,
        value = "12px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-type-reader-body-size",
        category = TokenCategory.Type,
        value = "18px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-type-reader-control-label-size",
        category = TokenCategory.Type,
        value = "12px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-xs",
        category = TokenCategory.Spacing,
        value = "8px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-sm",
        category = TokenCategory.Spacing,
        value = "12px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-md",
        category = TokenCategory.Spacing,
        value = "16px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-lg",
        category = TokenCategory.Spacing,
        value = "24px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-xl",
        category = TokenCategory.Spacing,
        value = "48px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-screen-padding",
        category = TokenCategory.Spacing,
        value = "16px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-card-padding",
        category = TokenCategory.Spacing,
        value = "14px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-safe-area-top",
        category = TokenCategory.Spacing,
        value = "24px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-safe-area-bottom",
        category = TokenCategory.Spacing,
        value = "14px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-safe-area-horizontal",
        category = TokenCategory.Spacing,
        value = "16px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-space-keyboard-gap",
        category = TokenCategory.Spacing,
        value = "12px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-phone-width",
        category = TokenCategory.Size,
        value = "390px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-phone-height",
        category = TokenCategory.Size,
        value = "844px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-stack-phone-height",
        category = TokenCategory.Size,
        value = "878px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-flow-width",
        category = TokenCategory.Size,
        value = "1284px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-flow-min-height",
        category = TokenCategory.Size,
        value = "520px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-top-bar-height",
        category = TokenCategory.Size,
        value = "58px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-bottom-bar-height",
        category = TokenCategory.Size,
        value = "68px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-main-nav-height",
        category = TokenCategory.Size,
        value = "68px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-reader-bottom-sheet-min-height",
        category = TokenCategory.Size,
        value = "284px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-reader-module-nav-height",
        category = TokenCategory.Size,
        value = "82px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-size-keyboard-height",
        category = TokenCategory.Size,
        value = "320px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-radius-small",
        category = TokenCategory.Radius,
        value = "4px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-radius-medium",
        category = TokenCategory.Radius,
        value = "6px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-radius-large",
        category = TokenCategory.Radius,
        value = "8px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-radius-card",
        category = TokenCategory.Radius,
        value = "4px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-radius-chip",
        category = TokenCategory.Radius,
        value = "2px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-radius-bottom-sheet",
        category = TokenCategory.Radius,
        value = "8px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-radius-control",
        category = TokenCategory.Radius,
        value = "999px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-elevation-none",
        category = TokenCategory.Elevation,
        value = "0px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-elevation-subtle",
        category = TokenCategory.Elevation,
        value = "1px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-elevation-card",
        category = TokenCategory.Elevation,
        value = "2px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-elevation-overlay",
        category = TokenCategory.Elevation,
        value = "2px",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-shadow-elevated",
        category = TokenCategory.Shadow,
        value = "0 18px 46px rgba(89,70,50,0.16)",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-shadow-soft",
        category = TokenCategory.Shadow,
        value = "0 8px 26px rgba(89,70,50,0.1)",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-state-focus",
        category = TokenCategory.Shadow,
        value = "0 0 0 4px rgba(54,97,121,0.22)",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-z-content",
        category = TokenCategory.ZIndex,
        value = "0",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-z-overlay",
        category = TokenCategory.ZIndex,
        value = "10",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-z-main-nav",
        category = TokenCategory.ZIndex,
        value = "20",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-z-bottom-sheet",
        category = TokenCategory.ZIndex,
        value = "30",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-z-reader-module-nav",
        category = TokenCategory.ZIndex,
        value = "40",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-z-dialog",
        category = TokenCategory.ZIndex,
        value = "60",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-z-keyboard",
        category = TokenCategory.ZIndex,
        value = "70",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-text-nav-label-lines",
        category = TokenCategory.TextConstraint,
        value = "1",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-text-title-lines",
        category = TokenCategory.TextConstraint,
        value = "1",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-text-book-title-lines",
        category = TokenCategory.TextConstraint,
        value = "2",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-text-reader-line-length",
        category = TokenCategory.TextConstraint,
        value = "31ch",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-text-action-label-lines",
        category = TokenCategory.TextConstraint,
        value = "1",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-firstOpen",
        category = TokenCategory.MotionDuration,
        value = "280ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-tabPress",
        category = TokenCategory.MotionDuration,
        value = "80ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-tabSelect",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-tabSwitch",
        category = TokenCategory.MotionDuration,
        value = "160ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-buttonPress",
        category = TokenCategory.MotionDuration,
        value = "80ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-buttonActivate",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-toggleSwitch",
        category = TokenCategory.MotionDuration,
        value = "140ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-chipSelect",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-filterCommit",
        category = TokenCategory.MotionDuration,
        value = "160ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-numericCommit",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-inputFocus",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-searchState",
        category = TokenCategory.MotionDuration,
        value = "160ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-feedbackToast",
        category = TokenCategory.MotionDuration,
        value = "180ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-stateReplace",
        category = TokenCategory.MotionDuration,
        value = "160ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-selectionToolbar",
        category = TokenCategory.MotionDuration,
        value = "160ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-dropdownPress",
        category = TokenCategory.MotionDuration,
        value = "80ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-dropdownExpand",
        category = TokenCategory.MotionDuration,
        value = "160ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-dropdownCollapse",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-dropdownSelect",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-readerInstant",
        category = TokenCategory.MotionDuration,
        value = "0ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-readerMicro",
        category = TokenCategory.MotionDuration,
        value = "80ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-readerFast",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-readerBase",
        category = TokenCategory.MotionDuration,
        value = "160ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-handleLongPress",
        category = TokenCategory.MotionDuration,
        value = "320ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-handleSnap",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-panel",
        category = TokenCategory.MotionDuration,
        value = "200ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-pageTurn",
        category = TokenCategory.MotionDuration,
        value = "220ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-readerEntry",
        category = TokenCategory.MotionDuration,
        value = "240ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-sessionReturn",
        category = TokenCategory.MotionDuration,
        value = "200ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-runningSpace",
        category = TokenCategory.MotionDuration,
        value = "180ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-capsuleEnter",
        category = TokenCategory.MotionDuration,
        value = "160ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-capsuleControl",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-capsuleTick",
        category = TokenCategory.MotionDuration,
        value = "120ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-voicePulse",
        category = TokenCategory.MotionDuration,
        value = "960ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-overlay",
        category = TokenCategory.MotionDuration,
        value = "240ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-loadingSpin",
        category = TokenCategory.MotionDuration,
        value = "800ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-interruptSettle",
        category = TokenCategory.MotionDuration,
        value = "80ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-viewportReshape",
        category = TokenCategory.MotionDuration,
        value = "240ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-orientationFreeze",
        category = TokenCategory.MotionDuration,
        value = "80ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-duration-orientationSettle",
        category = TokenCategory.MotionDuration,
        value = "240ms",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-easing-standard",
        category = TokenCategory.MotionEasing,
        value = "ease",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-easing-enter",
        category = TokenCategory.MotionEasing,
        value = "ease-out",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-easing-exit",
        category = TokenCategory.MotionEasing,
        value = "ease-in",
        platforms = null,
        deprecated = false
    ),
    Token(
        name = "--reader-ds-motion-easing-reshape",
        category = TokenCategory.MotionEasing,
        value = "ease-in-out",
        platforms = null,
        deprecated = false
    )
    )

    val byName: Map<String, Token> = all.associateBy { it.name }

    fun token(name: String): Token? = byName[name]
}
