// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/ui-state.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

@Serializable
enum class ReaderMode {
    @SerialName("default")
    Default,
    @SerialName("loading")
    Loading,
    @SerialName("empty")
    Empty,
    @SerialName("error")
    Error,
    @SerialName("offline")
    Offline,
    @SerialName("permission")
    Permission
}

@Serializable
enum class Overlay {
    @SerialName("settings")
    Settings,
    @SerialName("reader-control")
    ReaderControl,
    @SerialName("directory")
    Directory,
    @SerialName("tts")
    Tts,
    @SerialName("appearance")
    Appearance,
    @SerialName("auto-page")
    AutoPage,
    @SerialName("content-search")
    ContentSearch,
    @SerialName("content-replacement")
    ContentReplacement,
    @SerialName("source-switch")
    SourceSwitch,
    @SerialName("book-action")
    BookAction,
    @SerialName("sort-filter")
    SortFilter,
    @SerialName("group-management")
    GroupManagement,
    @SerialName("local-import")
    LocalImport,
    @SerialName("batch-management")
    BatchManagement,
    @SerialName("reader-night-state")
    ReaderNightState,
    @SerialName("reader-debug-info")
    ReaderDebugInfo,
    @SerialName("reader-book-cache")
    ReaderBookCache,
    @SerialName("keyboard")
    Keyboard,
    @SerialName("dialog")
    Dialog,
    @SerialName("sheet")
    Sheet,
    @SerialName("toast")
    Toast
}

@Serializable
enum class ActiveSession {
    @SerialName("reading")
    Reading,
    @SerialName("tts")
    Tts,
    @SerialName("auto-page")
    AutoPage
}

@Serializable
enum class PageState {
    @SerialName("default")
    Default,
    @SerialName("loading")
    Loading,
    @SerialName("empty")
    Empty,
    @SerialName("error")
    Error,
    @SerialName("offline")
    Offline,
    @SerialName("permission")
    Permission,
    @SerialName("cover-mode")
    CoverMode,
    @SerialName("list-mode")
    ListMode,
    @SerialName("shelf-empty")
    ShelfEmpty,
    @SerialName("no-cover")
    NoCover,
    @SerialName("long-title")
    LongTitle,
    @SerialName("switching-source-type")
    SwitchingSourceType,
    @SerialName("source-empty")
    SourceEmpty,
    @SerialName("source-unavailable")
    SourceUnavailable,
    @SerialName("network-failed")
    NetworkFailed,
    @SerialName("refreshing")
    Refreshing,
    @SerialName("no-subscription")
    NoSubscription,
    @SerialName("no-unread")
    NoUnread,
    @SerialName("local-data-loading")
    LocalDataLoading,
    @SerialName("no-backup")
    NoBackup,
    @SerialName("permission-missing")
    PermissionMissing,
    @SerialName("topbar-action")
    TopbarAction
}

@Serializable
data class UiError(
    val code: String,
    val message: String,
    val retryable: Boolean = false
)

@Serializable
data class RouteRef(
    val id: String,
    val params: Map<String, String> = emptyMap(),
    val stack: List<RouteRef>? = null
)

@Serializable
data class BookshelfUiState(
    val viewMode: String? = null,
    val selectedGroupId: String? = null,
    val sortKey: String? = null,
    val sortOrder: String? = null,
    val filterKeys: List<String>? = null
)

@Serializable
data class DiscoverUiState(
    val filter: String? = null,
    val sort: String? = null,
    val sortOpen: Boolean? = null,
    val sourceType: String? = null,
    val sourceEnabled: Map<String, Boolean>? = null
)

@Serializable
data class ReaderUiState(
    val turnDirection: String? = null,
    val pageIndex: Int? = null,
    val chapterIndex: Int? = null,
    val chapterProgress: Double? = null,
    val chapterDownloads: Map<String, String>? = null,
    val tts: Map<String, JsonElement>? = null,
    val settings: Map<String, JsonElement>? = null,
    val typography: Map<String, JsonElement>? = null,
    val textSelectionOpen: Boolean? = null,
    val selectedText: String? = null,
    val sessionCapsuleSnapshot: Map<String, JsonElement>? = null,
    val controlSpaceSnapshot: Map<String, JsonElement>? = null,
    val autoPageCountdown: Double? = null,
    val dockOffsets: Map<String, Double>? = null,
    val entryMotion: String? = null
)

@Serializable
data class SettingsUiState(
    val overlay: String? = null,
    val expandedOption: String? = null,
    val restoreAvailableScopes: List<String>? = null,
    val restoreSelectedScopes: List<String>? = null
)

@Serializable
data class MotionUiState(
    val overlaySequence: String? = null,
    val overlayRole: String? = null,
    val overlayAction: String? = null,
    val overlayFocusReturn: String? = null,
    val overlayReturnTarget: String? = null,
    val viewportOrientationMotion: String? = null,
    val viewportOrientationSequence: String? = null,
    val viewportOrientationTimer: Double? = null,
    val interruptMotion: String? = null,
    val interruptSequence: String? = null,
    val interruptTimer: Double? = null,
    val dropdownMotion: String? = null,
    val dropdownSwitchMotion: String? = null,
    val dropdownSwitchSequence: String? = null,
    val dropdownSwitchTimer: Double? = null,
    val segmentMotion: String? = null,
    val asyncRouteRequest: String? = null,
    val asyncResultMotion: String? = null,
    val asyncResultSequence: String? = null
)

@Serializable
data class FirstOpenUiState(
    val hasPlayed: Boolean? = null,
    val motionTimer: Double? = null
)

@Serializable
data class UiState(
    val route: RouteRef,
    val tab: MainTab,
    val readerMode: ReaderMode,
    val overlay: Overlay? = null,
    val activeSession: ActiveSession? = null,
    val focusTarget: String? = null,
    val loading: Boolean,
    val error: UiError? = null,
    val reducedMotion: Boolean = false,
    val pageState: PageState? = null,
    val bookshelf: BookshelfUiState? = null,
    val discover: DiscoverUiState? = null,
    val reader: ReaderUiState? = null,
    val settings: SettingsUiState? = null,
    val motion: MotionUiState? = null,
    val firstOpen: FirstOpenUiState? = null
)
