// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/view-state.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

@Serializable
enum class ComponentType {
    @SerialName("AppTopBar")
    AppTopBar,
    @SerialName("BackTopBar")
    BackTopBar,
    @SerialName("SearchEntry")
    SearchEntry,
    @SerialName("SourceTypeSegment")
    SourceTypeSegment,
    @SerialName("CurrentSourceCard")
    CurrentSourceCard,
    @SerialName("SourceCategoryChips")
    SourceCategoryChips,
    @SerialName("DiscoveryContentCard")
    DiscoveryContentCard,
    @SerialName("SourceStatusBar")
    SourceStatusBar,
    @SerialName("BottomNav")
    BottomNav,
    @SerialName("ShelfChipGroup")
    ShelfChipGroup,
    @SerialName("ContinueReadingCard")
    ContinueReadingCard,
    @SerialName("RecentUpdateCard")
    RecentUpdateCard,
    @SerialName("ShelfSectionHeader")
    ShelfSectionHeader,
    @SerialName("BookCard")
    BookCard,
    @SerialName("BookListItem")
    BookListItem,
    @SerialName("ProgressBar")
    ProgressBar,
    @SerialName("SubscriptionSummaryCard")
    SubscriptionSummaryCard,
    @SerialName("FeedStatusChips")
    FeedStatusChips,
    @SerialName("FeedSourceChips")
    FeedSourceChips,
    @SerialName("RssEntryItem")
    RssEntryItem,
    @SerialName("UnreadIndicator")
    UnreadIndicator,
    @SerialName("LocalOverviewCard")
    LocalOverviewCard,
    @SerialName("QuickEntryGrid")
    QuickEntryGrid,
    @SerialName("SettingsSection")
    SettingsSection,
    @SerialName("SettingsListItem")
    SettingsListItem,
    @SerialName("SearchInputBox")
    SearchInputBox,
    @SerialName("ScopeSelector")
    ScopeSelector,
    @SerialName("GroupSelector")
    GroupSelector,
    @SerialName("SearchHistoryList")
    SearchHistoryList,
    @SerialName("SearchResultList")
    SearchResultList,
    @SerialName("AddToShelfButton")
    AddToShelfButton,
    @SerialName("ReadButton")
    ReadButton,
    @SerialName("BookCover")
    BookCover,
    @SerialName("BookTitleAuthor")
    BookTitleAuthor,
    @SerialName("SourceStatus")
    SourceStatus,
    @SerialName("DirectoryPreview")
    DirectoryPreview,
    @SerialName("BookIntro")
    BookIntro,
    @SerialName("ConfigEntry")
    ConfigEntry,
    @SerialName("ReadingBackgroundLayer")
    ReadingBackgroundLayer,
    @SerialName("ReadingTextFlow")
    ReadingTextFlow,
    @SerialName("ReadingInfoLayer")
    ReadingInfoLayer,
    @SerialName("TapZones")
    TapZones,
    @SerialName("Loading")
    Loading,
    @SerialName("Empty")
    Empty,
    @SerialName("Error")
    Error,
    @SerialName("Offline")
    Offline,
    @SerialName("Permission")
    Permission,
    @SerialName("Toast")
    Toast,
    @SerialName("Sheet")
    Sheet,
    @SerialName("Dialog")
    Dialog,
    @SerialName("Overlay")
    Overlay,
    @SerialName("List")
    List,
    @SerialName("ListRow")
    ListRow,
    @SerialName("Card")
    Card,
    @SerialName("Chip")
    Chip,
    @SerialName("Button")
    Button,
    @SerialName("Toggle")
    Toggle,
    @SerialName("Slider")
    Slider,
    @SerialName("Stepper")
    Stepper,
    @SerialName("Segment")
    Segment,
    @SerialName("Dropdown")
    Dropdown,
    @SerialName("Input")
    Input,
    @SerialName("FormSection")
    FormSection,
    @SerialName("FilterBar")
    FilterBar,
    @SerialName("Content")
    Content,
    @SerialName("WebView")
    WebView
}

@Serializable
data class ViewStateComponent(
    val type: ComponentType,
    val id: String? = null,
    val props: Map<String, JsonElement>? = null,
    val children: List<ViewStateComponent>? = null
)

@Serializable
data class ViewState(
    val routeId: String,
    val pageState: PageState,
    val context: Map<String, JsonElement>? = null,
    val components: List<ViewStateComponent>
)
